version: '3'
services:
  twitter:
    build: twitter
    expose:
     - "5000"
    volumes:
     - ./twitter:/app
  db_iface:
    build: db_iface
    expose:
     - "5000"
    volumes:
     - ./db_iface:/app
    links:
     - "db"
    depends_on:
     - "db"
  db:
    build: db
    expose:
     - "5432"
    volumes:
     - pgdata:/var/lib/postgresql/data
  watson:
    build: watson
    expose:
     - "5000"
    volumes:
     - ./watson:/app
  filter:
    build: filter
    expose:
     - "5000"
    volumes:
     - ./filter:/app
  server:
    build: server
    ports:
     - "80:5000"
    volumes:
     - ./server:/app
    links:
     - "watson"
     - "twitter"
     - "filter"
     - "db_iface"
volumes:
  pgdata: